### ISSUE TITLE
Mala redacción en la evaluación técnica

### ISSUE THREAD

**Issue by LuisAlejandro** [Vauxoo/vauxoo-applicant#53]
En el ejercicio "py1" se dan las siguientes instrucciones:

> py1: Puedes realizar una clase en python llamada "prime_class" que tenga un método llamado "is_prime" y que reciba como entrada un número entero y que de salida regrese un True o False en boolean (no usar cadenas), para saber si sí es un número primo o no lo es, respectivamente.

Allí se lee claramente que la clase debe llamarse "prime_class", sin embargo, las pruebas unitarias referencian a la clase "PrimeClass", lo cuál resultaría en un fallo si se siguen las instrucciones a cabalidad.

De igualmente en el ejercicio "py2" se lee:

> py2: Puedes realizar una clase en python llamada "calculator_class" que tenga un método llamado "sum" y que reciba como entrada una lista de números números y que de salida regrese la suma de los mismos.

En donde se indica que la clase debe llamarse "calculator_class", pero las pruebas unitarias referencian a la clase "CalculatorClass".

Se recomienda corregir la redacción de la Evaluación para evitar confusiones futuras.

**Comment by moylop260** [comment]
Lo que se requiere es inyectar el error, para que puedan revisar el resultado del CI y su capacidad de solución.
Gracias por tu interes en mejorar la encuesta.

**Comment by LuisAlejandro** [comment]
Ah, perfecto.

A la orden.
